// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'disabled': string;
  'radio': string;
  'radio--inline': string;
  'radio--normal': string;
  'radio--small': string;
  'radio__checkmark': string;
  'radio__checkmark-container': string;
  'radio__input': string;
}
export const cssExports: CssExports;
export default cssExports;
