// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn--primary': string;
  'btn__base': string;
}
export const cssExports: CssExports;
export default cssExports;
