// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btn--ghost': string;
  'btn--lg': string;
  'btn--link': string;
  'btn--md': string;
  'btn--primary': string;
  'btn--secondary': string;
  'btn--sm': string;
  'btn--xs': string;
}
export const cssExports: CssExports;
export default cssExports;
