// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body-1': string;
  'body-2': string;
  'body-3': string;
  'body-4': string;
  'display-1': string;
  'display-2': string;
  'display-3': string;
  'heading-1': string;
  'heading-2': string;
  'heading-3': string;
  'heading-4': string;
  'heading-5': string;
  'heading-6': string;
  'input-border': string;
  'input-border-midpart': string;
  'input-border-midpart-content': string;
  'input-disabled': string;
  'input-error': string;
  'input-filled': string;
  'input-focused': string;
  'input-helper': string;
  'input-icon': string;
  'input-label': string;
  'input-leading': string;
  'input-prefix': string;
  'input-top': string;
  'input-trailing': string;
  'line-through': string;
  'none': string;
  'text--400': string;
  'text--700': string;
  'text--800': string;
  'underline': string;
}
export const cssExports: CssExports;
export default cssExports;
