// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contained-label': string;
  'input-border': string;
  'input-icon': string;
  'input-label': string;
  'none': string;
  'placeholder-text': string;
  'prefix': string;
  'suffix': string;
  'top-label': string;
}
export const cssExports: CssExports;
export default cssExports;
