// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body-1': string;
  'body-2': string;
  'body-3': string;
  'body-4': string;
  'defaultColor': string;
  'disabledColor': string;
  'display-1': string;
  'display-2': string;
  'display-3': string;
  'heading-1': string;
  'heading-2': string;
  'heading-3': string;
  'heading-4': string;
  'heading-5': string;
  'heading-6': string;
  'input-border': string;
  'input-border-margin-top': string;
  'input-border-mid-part': string;
  'input-border-mid-part-content': string;
  'input-border-mid-part-content-margin-right': string;
  'input-border-mid-part-margin-left': string;
  'input-border-mid-part-margin-right': string;
  'input-border-state-disabled': string;
  'input-border-state-error': string;
  'input-border-state-filled': string;
  'input-border-state-focus': string;
  'input-helper-text': string;
  'input-helper-text-state-disabled': string;
  'input-helper-text-state-error': string;
  'input-icon': string;
  'input-icon-disabled': string;
  'input-label': string;
  'input-label-state-disabled': string;
  'input-label-state-error': string;
  'line-through': string;
  'none': string;
  'text--400': string;
  'text--700': string;
  'text--800': string;
  'underline': string;
}
export const cssExports: CssExports;
export default cssExports;
