// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'checkbox__checkmark': string;
  'checkbox__checkmark__container': string;
  'checkbox__input': string;
  'disabled': string;
}
export const cssExports: CssExports;
export default cssExports;
