// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body-1': string;
  'body-2': string;
  'body-3': string;
  'body-4': string;
  'display-1': string;
  'display-2': string;
  'display-3': string;
  'heading-1': string;
  'heading-2': string;
  'heading-3': string;
  'heading-4': string;
  'heading-5': string;
  'heading-6': string;
  'text-line-through': string;
  'text-no-decoration': string;
  'text-underline': string;
}
export const cssExports: CssExports;
export default cssExports;
